// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJmyoUWby5HeoR1Dg83KLTP0qDKHDBMb4',
    appId: '1:381729906870:web:50f0a3335ada08ef858617',
    messagingSenderId: '381729906870',
    projectId: 'crtrack-e1147',
    authDomain: 'crtrack-e1147.firebaseapp.com',
    storageBucket: 'crtrack-e1147.appspot.com',
    measurementId: 'G-F9RV0S2V9E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQ8lOzDH4pb3-58Rfv1tKVyqGniYuO0UQ',
    appId: '1:381729906870:android:f51ac4bd352cf90f858617',
    messagingSenderId: '381729906870',
    projectId: 'crtrack-e1147',
    storageBucket: 'crtrack-e1147.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBB4BKNZn3qCBaBTE-_Pw5TxRfZlIEqyLU',
    appId: '1:381729906870:ios:a3d8304f25c49b64858617',
    messagingSenderId: '381729906870',
    projectId: 'crtrack-e1147',
    storageBucket: 'crtrack-e1147.appspot.com',
    iosBundleId: 'com.example.crt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBB4BKNZn3qCBaBTE-_Pw5TxRfZlIEqyLU',
    appId: '1:381729906870:ios:a3d8304f25c49b64858617',
    messagingSenderId: '381729906870',
    projectId: 'crtrack-e1147',
    storageBucket: 'crtrack-e1147.appspot.com',
    iosBundleId: 'com.example.crt',
  );

}